### ISSUE TITLE
got this error "UnicodeEncodeError: 'gbk' codec can't encode character '\ufeff' in position 0: illegal multibyte sequence"

### ISSUE THREAD

**Issue by bigdajj** [wayneclub/Subtitle-Downloader#3]
When download subtitles from line tv 

"https://www.linetv.tw/drama/12953/eps/1?col_index=0&drama_id=12953&source=INDEX_BANNER",

I got this error,Can you help me figure out what this error is 

![SCREENSHOT](https://user-images.githubusercontent.com/80830492/147847194-0af88907-334d-493a-8099-9ed468b54962.jpg)

**Comment by wayneclub** [comment]
I'd fixed the encoding issues, please try again.

**Comment by bigdajj** [comment]
Thank you for fixing these issues!

**Comment by bigdajj** [comment]
I still got another issue When download from KKTV and friday in Chinese colab and Windows , as the picture shows below.

![bug1](https://user-images.githubusercontent.com/80830492/148005154-ae0bcd45-bc27-4bf5-8dfb-fffad74cffd4.jpg)

While it works well in English Colab, I dont know the reason cause the codes are same

**Comment by bigdajj** [comment]
works well in English Colab

![issue1](https://user-images.githubusercontent.com/80830492/148005501-750a03fd-41db-45c3-afef-430b8b0d2376.jpg)

**Comment by bigdajj** [comment]
And Windows with this error

![bug2](https://user-images.githubusercontent.com/80830492/148020763-99df2474-3c0e-436d-92b3-d39e380976a1.jpg)

**Comment by wayneclub** [comment]
I'd add "lxml" library in requirements, and the translation problems are fixed. It should work now.

**Comment by bigdajj** [comment]
> 

Thank you very much for the help! I will try if it works.

**Comment by bigdajj** [comment]
lol Still get some  errors

![bug3](https://user-images.githubusercontent.com/80830492/148028291-f8e9c84f-55ad-4c0d-9abc-868c832e5066.jpg)

and with iq.com seems lack of some requirements

![bug4](https://user-images.githubusercontent.com/80830492/148028690-e4b20d30-eae4-4437-8a19-5b0b69befff9.jpg)

**Comment by wayneclub** [comment]
1. I can't replicate the first issue, you can use `-d` and upload the log file.
2. I'd changed the selenium requirements to auto-install chromedriver with pip, and it should fix downloading iq.com problems.

**Comment by bigdajj** [comment]
Thank you for your kindly help, The friday site is working now except one ott error

![bug5](https://user-images.githubusercontent.com/80830492/148072134-4e5d6544-174f-4a99-a1b0-902f397bddb9.jpg)

and iq.com still get the same error, I upload the log file if it helps.

[Subtitle-Downloader_2022-01-04_17-07-15.log](https://github.com/wayneclub/Subtitle-Downloader/files/7808174/Subtitle-Downloader_2022-01-04_17-07-15.log)

**Comment by wayneclub** [comment]
Oops. I accidentally commit the wrong code. I'd re-upload it.
